export const GET_DATA = 'GET_DATA'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE'
export const CREATE_SUCCESS = 'CREATE_SUCCESS'
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'

// Mitations Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
